name: Integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.1, 8.2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Install dependencies
        run: composer install
      - name: Run integration tests
        run: composer run integration
